#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezerwacja_Hotelowa_LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Baza_Danych")]
	public partial class Baza_Danych_LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKlient(Klient instance);
    partial void UpdateKlient(Klient instance);
    partial void DeleteKlient(Klient instance);
    partial void InsertPokoj(Pokoj instance);
    partial void UpdatePokoj(Pokoj instance);
    partial void DeletePokoj(Pokoj instance);
    partial void InsertPracownicy(Pracownicy instance);
    partial void UpdatePracownicy(Pracownicy instance);
    partial void DeletePracownicy(Pracownicy instance);
    partial void InsertRezerwacja(Rezerwacja instance);
    partial void UpdateRezerwacja(Rezerwacja instance);
    partial void DeleteRezerwacja(Rezerwacja instance);
    #endregion
		
		public Baza_Danych_LINQDataContext() : 
				base(global::Rezerwacja_Hotelowa_LINQ.Properties.Settings.Default.Baza_DanychConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Baza_Danych_LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Baza_Danych_LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Baza_Danych_LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Baza_Danych_LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Klient> Klients
		{
			get
			{
				return this.GetTable<Klient>();
			}
		}
		
		public System.Data.Linq.Table<Klient_Pokoj> Klient_Pokojs
		{
			get
			{
				return this.GetTable<Klient_Pokoj>();
			}
		}
		
		public System.Data.Linq.Table<Pokoj> Pokojs
		{
			get
			{
				return this.GetTable<Pokoj>();
			}
		}
		
		public System.Data.Linq.Table<Pracownicy> Pracownicies
		{
			get
			{
				return this.GetTable<Pracownicy>();
			}
		}
		
		public System.Data.Linq.Table<Rezerwacja> Rezerwacjas
		{
			get
			{
				return this.GetTable<Rezerwacja>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klient")]
	public partial class Klient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_klienta;
		
		private string _imie;
		
		private string _nazwisko;
		
		private string _adres_zamieszkania;
		
		private System.Nullable<int> _numer_karty;
		
		private string _login;
		
		private string _haslo;
		
		private EntitySet<Rezerwacja> _Rezerwacjas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klientaChanging(int value);
    partial void Onid_klientaChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void Onadres_zamieszkaniaChanging(string value);
    partial void Onadres_zamieszkaniaChanged();
    partial void Onnumer_kartyChanging(System.Nullable<int> value);
    partial void Onnumer_kartyChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnhasloChanging(string value);
    partial void OnhasloChanged();
    #endregion
		
		public Klient()
		{
			this._Rezerwacjas = new EntitySet<Rezerwacja>(new Action<Rezerwacja>(this.attach_Rezerwacjas), new Action<Rezerwacja>(this.detach_Rezerwacjas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					this.Onid_klientaChanging(value);
					this.SendPropertyChanging();
					this._id_klienta = value;
					this.SendPropertyChanged("id_klienta");
					this.Onid_klientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres_zamieszkania", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string adres_zamieszkania
		{
			get
			{
				return this._adres_zamieszkania;
			}
			set
			{
				if ((this._adres_zamieszkania != value))
				{
					this.Onadres_zamieszkaniaChanging(value);
					this.SendPropertyChanging();
					this._adres_zamieszkania = value;
					this.SendPropertyChanged("adres_zamieszkania");
					this.Onadres_zamieszkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numer_karty", DbType="Int")]
		public System.Nullable<int> numer_karty
		{
			get
			{
				return this._numer_karty;
			}
			set
			{
				if ((this._numer_karty != value))
				{
					this.Onnumer_kartyChanging(value);
					this.SendPropertyChanging();
					this._numer_karty = value;
					this.SendPropertyChanged("numer_karty");
					this.Onnumer_kartyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haslo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string haslo
		{
			get
			{
				return this._haslo;
			}
			set
			{
				if ((this._haslo != value))
				{
					this.OnhasloChanging(value);
					this.SendPropertyChanging();
					this._haslo = value;
					this.SendPropertyChanged("haslo");
					this.OnhasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klient_Rezerwacja", Storage="_Rezerwacjas", ThisKey="id_klienta", OtherKey="id_klienta")]
		public EntitySet<Rezerwacja> Rezerwacjas
		{
			get
			{
				return this._Rezerwacjas;
			}
			set
			{
				this._Rezerwacjas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rezerwacjas(Rezerwacja entity)
		{
			this.SendPropertyChanging();
			entity.Klient = this;
		}
		
		private void detach_Rezerwacjas(Rezerwacja entity)
		{
			this.SendPropertyChanging();
			entity.Klient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klient_Pokoj")]
	public partial class Klient_Pokoj
	{
		
		private int _id_klienta;
		
		private int _id_pokoju;
		
		public Klient_Pokoj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", DbType="Int NOT NULL")]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					this._id_klienta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pokoju", DbType="Int NOT NULL")]
		public int id_pokoju
		{
			get
			{
				return this._id_pokoju;
			}
			set
			{
				if ((this._id_pokoju != value))
				{
					this._id_pokoju = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pokoj")]
	public partial class Pokoj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pokoju;
		
		private int _pojemnosc;
		
		private string _wyposarzenie;
		
		private System.Nullable<bool> _stan;
		
		private decimal _cena_pokoju;
		
		private System.Nullable<System.DateTime> _rezerwacja_od;
		
		private System.Nullable<System.DateTime> _rezerwacja_do;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pokojuChanging(int value);
    partial void Onid_pokojuChanged();
    partial void OnpojemnoscChanging(int value);
    partial void OnpojemnoscChanged();
    partial void OnwyposarzenieChanging(string value);
    partial void OnwyposarzenieChanged();
    partial void OnstanChanging(System.Nullable<bool> value);
    partial void OnstanChanged();
    partial void Oncena_pokojuChanging(decimal value);
    partial void Oncena_pokojuChanged();
    partial void Onrezerwacja_odChanging(System.Nullable<System.DateTime> value);
    partial void Onrezerwacja_odChanged();
    partial void Onrezerwacja_doChanging(System.Nullable<System.DateTime> value);
    partial void Onrezerwacja_doChanged();
    #endregion
		
		public Pokoj()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pokoju", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pokoju
		{
			get
			{
				return this._id_pokoju;
			}
			set
			{
				if ((this._id_pokoju != value))
				{
					this.Onid_pokojuChanging(value);
					this.SendPropertyChanging();
					this._id_pokoju = value;
					this.SendPropertyChanged("id_pokoju");
					this.Onid_pokojuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pojemnosc", DbType="Int NOT NULL")]
		public int pojemnosc
		{
			get
			{
				return this._pojemnosc;
			}
			set
			{
				if ((this._pojemnosc != value))
				{
					this.OnpojemnoscChanging(value);
					this.SendPropertyChanging();
					this._pojemnosc = value;
					this.SendPropertyChanged("pojemnosc");
					this.OnpojemnoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wyposarzenie", DbType="VarChar(500)")]
		public string wyposarzenie
		{
			get
			{
				return this._wyposarzenie;
			}
			set
			{
				if ((this._wyposarzenie != value))
				{
					this.OnwyposarzenieChanging(value);
					this.SendPropertyChanging();
					this._wyposarzenie = value;
					this.SendPropertyChanged("wyposarzenie");
					this.OnwyposarzenieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stan", DbType="Bit")]
		public System.Nullable<bool> stan
		{
			get
			{
				return this._stan;
			}
			set
			{
				if ((this._stan != value))
				{
					this.OnstanChanging(value);
					this.SendPropertyChanging();
					this._stan = value;
					this.SendPropertyChanged("stan");
					this.OnstanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena_pokoju", DbType="Money NOT NULL")]
		public decimal cena_pokoju
		{
			get
			{
				return this._cena_pokoju;
			}
			set
			{
				if ((this._cena_pokoju != value))
				{
					this.Oncena_pokojuChanging(value);
					this.SendPropertyChanging();
					this._cena_pokoju = value;
					this.SendPropertyChanged("cena_pokoju");
					this.Oncena_pokojuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezerwacja_od", DbType="Date")]
		public System.Nullable<System.DateTime> rezerwacja_od
		{
			get
			{
				return this._rezerwacja_od;
			}
			set
			{
				if ((this._rezerwacja_od != value))
				{
					this.Onrezerwacja_odChanging(value);
					this.SendPropertyChanging();
					this._rezerwacja_od = value;
					this.SendPropertyChanged("rezerwacja_od");
					this.Onrezerwacja_odChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezerwacja_do", DbType="Date")]
		public System.Nullable<System.DateTime> rezerwacja_do
		{
			get
			{
				return this._rezerwacja_do;
			}
			set
			{
				if ((this._rezerwacja_do != value))
				{
					this.Onrezerwacja_doChanging(value);
					this.SendPropertyChanging();
					this._rezerwacja_do = value;
					this.SendPropertyChanged("rezerwacja_do");
					this.Onrezerwacja_doChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pracownicy")]
	public partial class Pracownicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pracownika;
		
		private string _login;
		
		private string _haslo;
		
		private string _imie;
		
		private string _nazwisko;
		
		private int _poziom_uprawnien;
		
		private System.Nullable<System.DateTime> _data_logowania;
		
		private EntitySet<Rezerwacja> _Rezerwacjas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pracownikaChanging(int value);
    partial void Onid_pracownikaChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnhasloChanging(string value);
    partial void OnhasloChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void Onpoziom_uprawnienChanging(int value);
    partial void Onpoziom_uprawnienChanged();
    partial void Ondata_logowaniaChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_logowaniaChanged();
    #endregion
		
		public Pracownicy()
		{
			this._Rezerwacjas = new EntitySet<Rezerwacja>(new Action<Rezerwacja>(this.attach_Rezerwacjas), new Action<Rezerwacja>(this.detach_Rezerwacjas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pracownika", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pracownika
		{
			get
			{
				return this._id_pracownika;
			}
			set
			{
				if ((this._id_pracownika != value))
				{
					this.Onid_pracownikaChanging(value);
					this.SendPropertyChanging();
					this._id_pracownika = value;
					this.SendPropertyChanged("id_pracownika");
					this.Onid_pracownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_haslo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string haslo
		{
			get
			{
				return this._haslo;
			}
			set
			{
				if ((this._haslo != value))
				{
					this.OnhasloChanging(value);
					this.SendPropertyChanging();
					this._haslo = value;
					this.SendPropertyChanged("haslo");
					this.OnhasloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poziom_uprawnien", DbType="Int NOT NULL")]
		public int poziom_uprawnien
		{
			get
			{
				return this._poziom_uprawnien;
			}
			set
			{
				if ((this._poziom_uprawnien != value))
				{
					this.Onpoziom_uprawnienChanging(value);
					this.SendPropertyChanging();
					this._poziom_uprawnien = value;
					this.SendPropertyChanged("poziom_uprawnien");
					this.Onpoziom_uprawnienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_logowania", DbType="Date")]
		public System.Nullable<System.DateTime> data_logowania
		{
			get
			{
				return this._data_logowania;
			}
			set
			{
				if ((this._data_logowania != value))
				{
					this.Ondata_logowaniaChanging(value);
					this.SendPropertyChanging();
					this._data_logowania = value;
					this.SendPropertyChanged("data_logowania");
					this.Ondata_logowaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pracownicy_Rezerwacja", Storage="_Rezerwacjas", ThisKey="id_pracownika", OtherKey="id_pracownika")]
		public EntitySet<Rezerwacja> Rezerwacjas
		{
			get
			{
				return this._Rezerwacjas;
			}
			set
			{
				this._Rezerwacjas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rezerwacjas(Rezerwacja entity)
		{
			this.SendPropertyChanging();
			entity.Pracownicy = this;
		}
		
		private void detach_Rezerwacjas(Rezerwacja entity)
		{
			this.SendPropertyChanging();
			entity.Pracownicy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rezerwacja")]
	public partial class Rezerwacja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_rezerwacji;
		
		private System.Nullable<int> _wolne_pokoje;
		
		private System.Nullable<int> _zajete_pokoje;
		
		private int _id_klienta;
		
		private int _id_pracownika;
		
		private EntityRef<Klient> _Klient;
		
		private EntityRef<Pracownicy> _Pracownicy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rezerwacjiChanging(int value);
    partial void Onid_rezerwacjiChanged();
    partial void Onwolne_pokojeChanging(System.Nullable<int> value);
    partial void Onwolne_pokojeChanged();
    partial void Onzajete_pokojeChanging(System.Nullable<int> value);
    partial void Onzajete_pokojeChanged();
    partial void Onid_klientaChanging(int value);
    partial void Onid_klientaChanged();
    partial void Onid_pracownikaChanging(int value);
    partial void Onid_pracownikaChanged();
    #endregion
		
		public Rezerwacja()
		{
			this._Klient = default(EntityRef<Klient>);
			this._Pracownicy = default(EntityRef<Pracownicy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rezerwacji", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_rezerwacji
		{
			get
			{
				return this._id_rezerwacji;
			}
			set
			{
				if ((this._id_rezerwacji != value))
				{
					this.Onid_rezerwacjiChanging(value);
					this.SendPropertyChanging();
					this._id_rezerwacji = value;
					this.SendPropertyChanged("id_rezerwacji");
					this.Onid_rezerwacjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wolne_pokoje", DbType="Int")]
		public System.Nullable<int> wolne_pokoje
		{
			get
			{
				return this._wolne_pokoje;
			}
			set
			{
				if ((this._wolne_pokoje != value))
				{
					this.Onwolne_pokojeChanging(value);
					this.SendPropertyChanging();
					this._wolne_pokoje = value;
					this.SendPropertyChanged("wolne_pokoje");
					this.Onwolne_pokojeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zajete_pokoje", DbType="Int")]
		public System.Nullable<int> zajete_pokoje
		{
			get
			{
				return this._zajete_pokoje;
			}
			set
			{
				if ((this._zajete_pokoje != value))
				{
					this.Onzajete_pokojeChanging(value);
					this.SendPropertyChanging();
					this._zajete_pokoje = value;
					this.SendPropertyChanged("zajete_pokoje");
					this.Onzajete_pokojeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klienta", DbType="Int NOT NULL")]
		public int id_klienta
		{
			get
			{
				return this._id_klienta;
			}
			set
			{
				if ((this._id_klienta != value))
				{
					if (this._Klient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_klientaChanging(value);
					this.SendPropertyChanging();
					this._id_klienta = value;
					this.SendPropertyChanged("id_klienta");
					this.Onid_klientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pracownika", DbType="Int NOT NULL")]
		public int id_pracownika
		{
			get
			{
				return this._id_pracownika;
			}
			set
			{
				if ((this._id_pracownika != value))
				{
					if (this._Pracownicy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pracownikaChanging(value);
					this.SendPropertyChanging();
					this._id_pracownika = value;
					this.SendPropertyChanged("id_pracownika");
					this.Onid_pracownikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klient_Rezerwacja", Storage="_Klient", ThisKey="id_klienta", OtherKey="id_klienta", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Klient Klient
		{
			get
			{
				return this._Klient.Entity;
			}
			set
			{
				Klient previousValue = this._Klient.Entity;
				if (((previousValue != value) 
							|| (this._Klient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klient.Entity = null;
						previousValue.Rezerwacjas.Remove(this);
					}
					this._Klient.Entity = value;
					if ((value != null))
					{
						value.Rezerwacjas.Add(this);
						this._id_klienta = value.id_klienta;
					}
					else
					{
						this._id_klienta = default(int);
					}
					this.SendPropertyChanged("Klient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pracownicy_Rezerwacja", Storage="_Pracownicy", ThisKey="id_pracownika", OtherKey="id_pracownika", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Pracownicy Pracownicy
		{
			get
			{
				return this._Pracownicy.Entity;
			}
			set
			{
				Pracownicy previousValue = this._Pracownicy.Entity;
				if (((previousValue != value) 
							|| (this._Pracownicy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pracownicy.Entity = null;
						previousValue.Rezerwacjas.Remove(this);
					}
					this._Pracownicy.Entity = value;
					if ((value != null))
					{
						value.Rezerwacjas.Add(this);
						this._id_pracownika = value.id_pracownika;
					}
					else
					{
						this._id_pracownika = default(int);
					}
					this.SendPropertyChanged("Pracownicy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
